# Generated by Django 4.0 on 2022-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='plugins',
            field=models.JSONField(default=[]),
        ),
    ]
