# Generated by Django 4.0 on 2022-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_plugins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='plugins',
            field=models.JSONField(default=list),
        ),
    ]
