# Generated by Django 4.0 on 2022-09-09 19:39

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gaminglobby',
            name='active_game',
        ),
        migrations.RemoveField(
            model_name='gaminglobby',
            name='players',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='players',
        ),
        migrations.RemoveField(
            model_name='otscore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playerroundstat',
            name='game_team',
        ),
        migrations.RemoveField(
            model_name='playerroundstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='started',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=api.models.Game.Status['NOT_STARTED']),
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
        migrations.DeleteModel(
            name='GamingLobby',
        ),
        migrations.DeleteModel(
            name='Hub',
        ),
        migrations.DeleteModel(
            name='OtScore',
        ),
        migrations.DeleteModel(
            name='PlayerRoundStat',
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AddField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ingameteam'),
        ),
        migrations.AlterField(
            model_name='gameplayerevent',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.round'),
        ),
    ]
