# Generated by Django 4.0 on 2022-09-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappickprocess',
            name='turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
