# Generated by Django 4.0 on 2022-09-25 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mappick_map_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='blacklist',
            field=models.ManyToManyField(related_name='blacklisted_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='whitelist',
            field=models.ManyToManyField(related_name='whitelisted_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
