# Generated by Django 4.0 on 2022-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.IntegerField(),
        ),
    ]
