# Generated by Django 4.0 on 2022-10-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_playerqueue_queuedplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerqueue',
            name='captain_a',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.player'),
        ),
        migrations.AddField(
            model_name='playerqueue',
            name='captain_b',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.player'),
        ),
        migrations.AddField(
            model_name='playerqueue',
            name='match',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.event'),
        ),
        migrations.AlterField(
            model_name='queuedplayer',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.playerqueue'),
        ),
    ]
