# Generated by Django 4.0 on 2022-10-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_playerqueue_players_delete_queuedplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerqueue',
            old_name='open',
            new_name='locked',
        ),
    ]
