# Generated by Django 4.0 on 2022-10-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_open_playerqueue_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerqueue',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlayerConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerqueue')),
            ],
        ),
    ]
