# Generated by Django 4.0 on 2022-10-30 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_playerqueue_locked_playerconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerqueue',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerqueue',
            name='locked_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='playerqueue',
            name='team_a',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerqueue',
            name='team_b',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
