# Generated by Django 4.0 on 2022-11-01 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mappickprocess_picker_a_mappickprocess_picker_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingameteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerqueue',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='playerqueue',
            name='team_b',
        ),
        migrations.AddField(
            model_name='game',
            name='config_overrides',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='playersession',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersession',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playersession',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.ingameteam'),
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='ingameteam',
            name='match_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_game_team', to='api.matchteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_1', to='api.matchteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_2', to='api.matchteam'),
        ),
    ]
