# Generated by Django 4.0 on 2022-11-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_ingameteam_team_remove_playerqueue_team_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='api.matchteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='api.matchteam'),
        ),
    ]
