# Generated by Django 4.0 on 2022-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_match_team_one_alter_match_team_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingameteam',
            name='name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
