# Generated by Django 4.0 on 2022-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_ingameteam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
