# Generated by Django 4.0 on 2022-11-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_article_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='map',
        ),
        migrations.RemoveField(
            model_name='mappick',
            name='map_codename',
        ),
        migrations.RemoveField(
            model_name='mappick',
            name='map_name',
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_one', to='api.matchteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_two', to='api.matchteam'),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('tags', models.ManyToManyField(to='api.MapTag')),
            ],
        ),
        migrations.AddField(
            model_name='mappick',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.map'),
        ),
    ]
