# Generated by Django 4.0 on 2022-11-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_maptag_remove_game_map_remove_mappick_map_codename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.map'),
        ),
    ]
