# Generated by Django 4.0 on 2022-11-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_game_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.map'),
            preserve_default=False,
        ),
    ]
