# Generated by Django 4.0 on 2022-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_game_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_server',
            field=models.BooleanField(default=False),
        ),
    ]
